language: node_js
branches:
  only:
    - master
    - /^greenkeeper\/.*$/
node_js:
  - "node"
script: npm run ci
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local_dir: dist
  on:
    all_branches: true
