[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://gwa-calc.netlify.com/*"
  to = "https://calc.jared.gq/:splat"
  status = 301

[[redirects]]
  from = "http://gwa-calc.netlify.com/*"
  to = "https://calc.jared.gq/:splat"
  status = 301